---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: squirrel-manager
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - mutatingwebhookconfigurations
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - admissionregistration.k8s.io
  resourceNames:
  - squirrel-image-rewrite
  resources:
  - mutatingwebhookconfigurations
  verbs:
  - patch
  - update
- apiGroups:
  - squirrel.molier.dev
  resources:
  - clusterimagepolicies
  - imagepolicies
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - squirrel.molier.dev
  resources:
  - clusterimagepolicies/status
  - imagepolicies/status
  verbs:
  - get
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: squirrel-manager
  namespace: squirrel-system
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
- apiGroups:
  - ""
  resourceNames:
  - squirrel-webhook-tls
  resources:
  - secrets
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
